CREATE DATABASE DMC_CTRL;

CREATE TABLE PERFIL(
IN_ID_PERFIL INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
VC_DESCRIPCION VARCHAR(30) 
);


CREATE TABLE USUARIO(
CH_ID_USUARIO CHAR(30) PRIMARY KEY NOT NULL,
VC_NOMBRE VARCHAR(50),
VC_APELLIDOS VARCHAR(100),
IN_ID_PERFIL INT,
VC_PASSWORD VARCHAR(100),
VC_EMAIL VARCHAR(100)
);
ALTER TABLE USUARIO ADD CONSTRAINT FK_PERFIL FOREIGN KEY(IN_ID_PERFIL)
REFERENCES PERFIL(IN_ID_PERFIL);


CREATE TABLE PROVEEDOR(
IN_ID_PROVEEDOR INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
VC_NOMBRE VARCHAR(50),
VC_DESCRIPCION VARCHAR(500),
VC_EMAIL VARCHAR(100),
CH_ID_USUARIO_CREACION CHAR(30),
DT_FECHA_CREACION DATETIME,
CH_ID_USUARIO_UPDATE CHAR(30),
DT_FECHA_UPDATE DATETIME
);
ALTER TABLE PROVEEDOR ADD CONSTRAINT FK_USU1 FOREIGN KEY(CH_ID_USUARIO_CREACION)
REFERENCES USUARIO(CH_ID_USUARIO);
ALTER TABLE PROVEEDOR ADD CONSTRAINT FK_USU2 FOREIGN KEY(CH_ID_USUARIO_UPDATE)
REFERENCES USUARIO(CH_ID_USUARIO);

CREATE TABLE PROYECTO(
IN_ID_PROYECTO INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
VC_NOMBRE VARCHAR(50),
VC_DESCRIPCION VARCHAR(500),
CH_ID_USUARIO_CREACION CHAR(30),
DT_FECHA_CREACION DATETIME,
CH_ID_USUARIO_UPDATE CHAR(30),
DT_FECHA_UPDATE DATETIME,
IN_ID_PROVEEDOR INTEGER
);
ALTER TABLE PROYECTO ADD CONSTRAINT FK_PROV FOREIGN KEY(IN_ID_PROVEEDOR) 
REFERENCES PROVEEDOR(IN_ID_PROVEEDOR);
ALTER TABLE PROYECTO ADD CONSTRAINT FK_USU1_PROY FOREIGN KEY(CH_ID_USUARIO_CREACION)
REFERENCES USUARIO(CH_ID_USUARIO);
ALTER TABLE PROYECTO ADD CONSTRAINT FK_USU2_PROY FOREIGN KEY(CH_ID_USUARIO_UPDATE)
REFERENCES USUARIO(CH_ID_USUARIO);

CREATE TABLE PLANO(
IN_ID_PLANO INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
VC_NOMBRE VARCHAR(50),
VC_DESCRIPCION VARCHAR(500),
DT_FECHA_FIN DATETIME,
CH_ID_USUARIO_CREACION CHAR(30),
DT_FECHA_CREACION DATETIME,
CH_ID_USUARIO_UPDATE CHAR(30),
DT_FECHA_UPDATE DATETIME,
IN_ID_PROYECTO INTEGER
);
ALTER TABLE PLANO ADD CONSTRAINT FK_PROY FOREIGN KEY(IN_ID_PROYECTO) 
REFERENCES PROYECTO(IN_ID_PROYECTO);
ALTER TABLE PLANO ADD CONSTRAINT FK_USU1_PLA FOREIGN KEY(CH_ID_USUARIO_CREACION)
REFERENCES USUARIO(CH_ID_USUARIO);
ALTER TABLE PLANO ADD CONSTRAINT FK_USU2_PLA FOREIGN KEY(CH_ID_USUARIO_UPDATE)
REFERENCES USUARIO(CH_ID_USUARIO);

CREATE TABLE DOCUMENTO_MAESTRO(
IN_ID_DOC_MAESTRO INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
IN_ID_PROYECTO INTEGER,
CH_ID_USUARIO_CREACION CHAR(30),
DT_FECHA_CREACION DATETIME,
CH_ID_USUARIO_UPDATE CHAR(30),
DT_FECHA_UPDATE DATETIME
);
ALTER TABLE DOCUMENTO_MAESTRO ADD CONSTRAINT FK_DOC_MASTER_1 FOREIGN KEY(IN_ID_PROYECTO)
REFERENCES PROYECTO(IN_ID_PROYECTO);
ALTER TABLE DOCUMENTO_MAESTRO ADD CONSTRAINT FK_DOC_MASTER_2 FOREIGN KEY(CH_ID_USUARIO_CREACION)
REFERENCES USUARIO(CH_ID_USUARIO);
ALTER TABLE DOCUMENTO_MAESTRO ADD CONSTRAINT FK_DOC_MASTER_3 FOREIGN KEY(CH_ID_USUARIO_UPDATE)
REFERENCES USUARIO(CH_ID_USUARIO);

CREATE TABLE DOCUMENTO_PLANO(
IN_ID_DOC_PLANO INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
IN_ID_DOC_MAESTRO INTEGER,
IN_ID_PLANO INTEGER,
CH_ID_USUARIO_CREACION CHAR(30),
DT_FECHA_CREACION DATETIME,
CH_ID_USUARIO_UPDATE CHAR(30),
DT_FECHA_UPDATE DATETIME
);
ALTER TABLE DOCUMENTO_PLANO ADD CONSTRAINT FK_DOC_PLANO_1 FOREIGN KEY(IN_ID_DOC_MAESTRO)
REFERENCES DOCUMENTO_MAESTRO(IN_ID_DOC_MAESTRO);
ALTER TABLE DOCUMENTO_PLANO ADD CONSTRAINT FK_DOC_PLANO_2 FOREIGN KEY(IN_ID_PLANO)
REFERENCES PLANO(IN_ID_PLANO);
ALTER TABLE DOCUMENTO_PLANO ADD CONSTRAINT FK_DOC_PLANO_3 FOREIGN KEY(CH_ID_USUARIO_CREACION)
REFERENCES USUARIO(CH_ID_USUARIO);
ALTER TABLE DOCUMENTO_PLANO ADD CONSTRAINT FK_DOC_PLANO_4 FOREIGN KEY(CH_ID_USUARIO_UPDATE)
REFERENCES USUARIO(CH_ID_USUARIO);

CREATE TABLE DOCPLANO_USUARIO_DETALLE(
CH_ID_USUARIO CHAR(30),
IN_ID_DOC_PLANO INTEGER,
CH_ID_USUARIO_CREACION CHAR(30),
DT_FECHA_CREACION DATETIME,
CH_ID_USUARIO_UPDATE CHAR(30),
DT_FECHA_UPDATE DATETIME
);
ALTER TABLE DOCPLANO_USUARIO_DETALLE ADD CONSTRAINT FK_PLAN_USER_1 FOREIGN KEY(CH_ID_USUARIO)
REFERENCES USUARIO(CH_ID_USUARIO);
ALTER TABLE DOCPLANO_USUARIO_DETALLE ADD CONSTRAINT FK_PLAN_USER_2 FOREIGN KEY(IN_ID_DOC_PLANO)
REFERENCES DOCUMENTO_PLANO(IN_ID_DOC_PLANO);
ALTER TABLE DOCPLANO_USUARIO_DETALLE ADD CONSTRAINT FK_PLAN_USER_3 FOREIGN KEY(CH_ID_USUARIO_CREACION)
REFERENCES USUARIO(CH_ID_USUARIO);
ALTER TABLE DOCPLANO_USUARIO_DETALLE ADD CONSTRAINT FK_PLAN_USER_4 FOREIGN KEY(CH_ID_USUARIO_UPDATE)
REFERENCES USUARIO(CH_ID_USUARIO);

CREATE TABLE CAMPOS_DOCUMENTO_MAESTRO(
IN_ID_CAMPO INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
IN_ID_DOC_MAESTRO INTEGER,
VC_VALOR_CADENA_1 VARCHAR(200), -- DESCRIPCION DEL CAMPO
VC_VALOR_CADENA_2 VARCHAR(200),	-- RUTA DEL ARCHIVO DE IMAGEN
VC_VALOR_CADENA_3 VARCHAR(200),
VC_VALOR_CADENA_4 VARCHAR(200),
NU_VALOR_NUMERICO_1 NUMERIC,
NU_VALOR_NUMERICO_2 NUMERIC,
IN_VALOR_ENTERO_1 INTEGER,
IN_VALOR_ENTERO_2 INTEGER,
BL_VALOR_BOOLEANO_1 BOOL,
BL_VALOR_BOOLEANO_2 BOOL,
CH_ID_USUARIO_CREACION CHAR(30),
DT_FECHA_CREACION DATETIME,
CH_ID_USUARIO_UPDATE CHAR(30),
DT_FECHA_UPDATE DATETIME
);
ALTER TABLE CAMPOS_DOCUMENTO_MAESTRO ADD CONSTRAINT FK_CDM_1 FOREIGN KEY(IN_ID_DOC_MAESTRO)
REFERENCES DOCUMENTO_MAESTRO(IN_ID_DOC_MAESTRO);
ALTER TABLE CAMPOS_DOCUMENTO_MAESTRO ADD CONSTRAINT FK_CMD_2 FOREIGN KEY(CH_ID_USUARIO_CREACION)
REFERENCES USUARIO(CH_ID_USUARIO);
ALTER TABLE CAMPOS_DOCUMENTO_MAESTRO ADD CONSTRAINT FK_CMD_3 FOREIGN KEY(CH_ID_USUARIO_UPDATE)
REFERENCES USUARIO(CH_ID_USUARIO);

CREATE TABLE CAMPOS_DOCUMENTO_PLANO (
IN_ID_CAMPO INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
IN_ID_DOC_PLANO INTEGER,
VC_VALOR_CADENA_1 VARCHAR(200), -- VALOR DE CAMPO
VC_VALOR_CADENA_2 VARCHAR(200), -- ID DEL CAMPO AL QUE PERTENECE
VC_VALOR_CADENA_3 VARCHAR(200),
VC_VALOR_CADENA_4 VARCHAR(200),
NU_VALOR_NUMERICO_1 NUMERIC,
NU_VALOR_NUMERICO_2 NUMERIC,
IN_VALOR_ENTERO_1 INTEGER,
IN_VALOR_ENTERO_2 INTEGER,
BL_VALOR_BOOLEANO_1 BOOL,
BL_VALOR_BOOLEANO_2 BOOL,
CH_ID_USUARIO_CREACION CHAR(30),
DT_FECHA_CREACION DATETIME,
CH_ID_USUARIO_UPDATE CHAR(30),
DT_FECHA_UPDATE DATETIME
);
ALTER TABLE CAMPOS_DOCUMENTO_PLANO ADD CONSTRAINT FK_CDP_1 FOREIGN KEY(IN_ID_DOC_PLANO)
REFERENCES DOCUMENTO_PLANO(IN_ID_DOC_PLANO);
ALTER TABLE CAMPOS_DOCUMENTO_PLANO ADD CONSTRAINT FK_CDP_2 FOREIGN KEY(CH_ID_USUARIO_CREACION)
REFERENCES USUARIO(CH_ID_USUARIO);
ALTER TABLE CAMPOS_DOCUMENTO_PLANO ADD CONSTRAINT FK_CDP_3 FOREIGN KEY(CH_ID_USUARIO_UPDATE)
REFERENCES USUARIO(CH_ID_USUARIO);

-- PROCEDIMIENTOS ALMACENADOS 
CREATE PROCEDURE USP_LISTAR_DOCUMENTOS 
(IN ID_USUARIO CHAR(30))
BEGIN
	SELECT PR.VC_NOMBRE PROVEEDOR, PY.VC_NOMBRE PROYECTO, PL.VC_NOMBRE PLANO,
				DUD.IN_ID_DOC_PLANO IDDOCUMENTO,DUD.CH_ID_USUARIO USUARIO,PL.DT_FECHA_FIN FECHAENTREGA
	FROM PROVEEDOR PR INNER JOIN PROYECTO PY 
	ON PR.IN_ID_PROVEEDOR = PY.IN_ID_PROVEEDOR
	INNER JOIN PLANO PL ON PL.IN_ID_PROYECTO = PY.IN_ID_PROYECTO
	INNER JOIN DOCUMENTO_PLANO DP ON DP.IN_ID_PLANO = PL.IN_ID_PLANO 
	INNER JOIN DOCPLANO_USUARIO_DETALLE DUD ON DUD.IN_ID_DOC_PLANO = DP.IN_ID_PLANO
	WHERE DUD.CH_ID_USUARIO = ID_USUARIO;
END

CREATE PROCEDURE USP_LISTAR_DOCUMENTOS_ADM
(IN OPCION CHAR(1), VALOR VARCHAR(50))
BEGIN
	IF (OPCION = '0' AND VALOR ='') THEN 
		SELECT PR.VC_NOMBRE PROVEEDOR, PY.VC_NOMBRE PROYECTO, PL.VC_NOMBRE PLANO,
				DUD.IN_ID_DOC_PLANO IDDOCUMENTO,DUD.CH_ID_USUARIO USUARIO,PL.DT_FECHA_FIN FECHAENTREGA
		FROM PROVEEDOR PR INNER JOIN PROYECTO PY 
		ON PR.IN_ID_PROVEEDOR = PY.IN_ID_PROVEEDOR
		INNER JOIN PLANO PL ON PL.IN_ID_PROYECTO = PY.IN_ID_PROYECTO
		INNER JOIN DOCUMENTO_PLANO DP ON DP.IN_ID_PLANO = PL.IN_ID_PLANO 
		INNER JOIN DOCPLANO_USUARIO_DETALLE DUD ON DUD.IN_ID_DOC_PLANO = DP.IN_ID_PLANO
		ORDER BY PL.DT_FECHA_FIN DESC;
	ELSEIF( OPCION = '1') THEN
		SELECT PR.VC_NOMBRE PROVEEDOR, PY.VC_NOMBRE PROYECTO, PL.VC_NOMBRE PLANO,
				DUD.IN_ID_DOC_PLANO IDDOCUMENTO,DUD.CH_ID_USUARIO USUARIO,PL.DT_FECHA_FIN FECHAENTREGA
		FROM PROVEEDOR PR INNER JOIN PROYECTO PY 
		ON PR.IN_ID_PROVEEDOR = PY.IN_ID_PROVEEDOR
		INNER JOIN PLANO PL ON PL.IN_ID_PROYECTO = PY.IN_ID_PROYECTO
		INNER JOIN DOCUMENTO_PLANO DP ON DP.IN_ID_PLANO = PL.IN_ID_PLANO 
		INNER JOIN DOCPLANO_USUARIO_DETALLE DUD ON DUD.IN_ID_DOC_PLANO = DP.IN_ID_PLANO
		WHERE DUD.CH_ID_USUARIO LIKE CONCAT('%',VALOR,'%');
	ELSEIF (OPCION = '2') THEN
		SELECT PR.VC_NOMBRE PROVEEDOR, PY.VC_NOMBRE PROYECTO, PL.VC_NOMBRE PLANO,
				DUD.IN_ID_DOC_PLANO IDDOCUMENTO,DUD.CH_ID_USUARIO USUARIO,PL.DT_FECHA_FIN FECHAENTREGA
		FROM PROVEEDOR PR INNER JOIN PROYECTO PY 
		ON PR.IN_ID_PROVEEDOR = PY.IN_ID_PROVEEDOR
		INNER JOIN PLANO PL ON PL.IN_ID_PROYECTO = PY.IN_ID_PROYECTO
		INNER JOIN DOCUMENTO_PLANO DP ON DP.IN_ID_PLANO = PL.IN_ID_PLANO 
		INNER JOIN DOCPLANO_USUARIO_DETALLE DUD ON DUD.IN_ID_DOC_PLANO = DP.IN_ID_PLANO
		WHERE PR.VC_NOMBRE LIKE CONCAT('%',VALOR,'%');
	ELSEIF(OPCION = '3') THEN
		SELECT PR.VC_NOMBRE PROVEEDOR, PY.VC_NOMBRE PROYECTO, PL.VC_NOMBRE PLANO,
				DUD.IN_ID_DOC_PLANO IDDOCUMENTO,DUD.CH_ID_USUARIO USUARIO,PL.DT_FECHA_FIN FECHAENTREGA
		FROM PROVEEDOR PR INNER JOIN PROYECTO PY 
		ON PR.IN_ID_PROVEEDOR = PY.IN_ID_PROVEEDOR
		INNER JOIN PLANO PL ON PL.IN_ID_PROYECTO = PY.IN_ID_PROYECTO
		INNER JOIN DOCUMENTO_PLANO DP ON DP.IN_ID_PLANO = PL.IN_ID_PLANO 
		INNER JOIN DOCPLANO_USUARIO_DETALLE DUD ON DUD.IN_ID_DOC_PLANO = DP.IN_ID_PLANO
		WHERE PY.VC_NOMBRE LIKE CONCAT('%',VALOR,'%');
	ELSEIF (OPCION = '4') THEN
		SELECT PR.VC_NOMBRE PROVEEDOR, PY.VC_NOMBRE PROYECTO, PL.VC_NOMBRE PLANO,
				DUD.IN_ID_DOC_PLANO IDDOCUMENTO,DUD.CH_ID_USUARIO USUARIO,PL.DT_FECHA_FIN FECHAENTREGA
		FROM PROVEEDOR PR INNER JOIN PROYECTO PY 
		ON PR.IN_ID_PROVEEDOR = PY.IN_ID_PROVEEDOR
		INNER JOIN PLANO PL ON PL.IN_ID_PROYECTO = PY.IN_ID_PROYECTO
		INNER JOIN DOCUMENTO_PLANO DP ON DP.IN_ID_PLANO = PL.IN_ID_PLANO 
		INNER JOIN DOCPLANO_USUARIO_DETALLE DUD ON DUD.IN_ID_DOC_PLANO = DP.IN_ID_PLANO
		WHERE PL.VC_NOMBRE LIKE CONCAT('%',VALOR,'%');
	END IF;
END